backend/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
     resources :investors
    end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/investor.rb
class Investor < ApplicationRecord
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :dateOfBirth, presence: true
  validates :phoneNumber, presence: true
  validates :streetAddress, presence: true
  validates :state, presence: true
  validates :zipCode, presence: true
end

backend/app/controllers/api/v1/investors_controller.rb
require 'pry'

class Api::V1::InvestorsController < ApplicationController

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.create(investor_params)
    if @investor.valid?
      render json: @investor
    else 
      render json: @investor.errors.full_messages
    end
    
  end

  private

    # Only allow a list of trusted parameters through.
    def investor_params
      params.require(:investor).permit(:firstName, :lastName, :dateOfBirth, :phoneNumber, :streetAddress, :state, :zipCode, :file)  
    end
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/investors_helper.rb
module InvestorsHelper
end

backend/app/views/investors/_form.html.erb
<%= form_with(model: investor, local: true) do |form| %>
  <% if investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% investor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/investors/edit.html.erb
<h1>Editing Investor</h1>

<%= render 'form', investor: @investor %>

<%= link_to 'Show', @investor %> |
<%= link_to 'Back', investors_path %>

backend/app/views/investors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investors</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investors.each do |investor| %>
      <tr>
        <td><%= investor.firstName %></td>
        <td><%= investor.lastName %></td>
        <td><%= link_to 'Show', investor %></td>
        <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
        <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investor', new_investor_path %>

backend/app/views/investors/new.html.erb
<h1>New Investor</h1>

<%= render 'form', investor: @investor %>

<%= link_to 'Back', investors_path %>

backend/app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @investor.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @investor.lastName %>
</p>

<%= link_to 'Edit', edit_investor_path(@investor) %> |
<%= link_to 'Back', investors_path %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvestorApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>